### ISSUE TITLE
CRDTs: State synchronization and renderer

### ISSUE THREAD

**Issue by fenhz** [decentraland/adr#117]
### Abstract
This document intention is to describe the current problem with the synchronization of state of scenes and renderer and therefore, the evaluated alternatives and options to deal with these specific issues through different CRDT algorithms in order to optimize performance by preserving and reproducing 'user intention' in a more consistent and reasonable way.

**Comment by fenhz** [comment]
@gonpombo8

**Comment by menduz** [comment]
WIP https://github.com/decentraland/adr/pull/122
